name = "workers-proxy"
main = "src/index.js"
compatibility_date = "2026-03-20"
compatibility_flags = ["global_fetch_strictly_public"]

[build]
command = "npm run build"

# This rule allows us to import our raw HTML and JS files as strings in the Worker
[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.raw.js"]
fallbacks = []

[[d1_databases]]
binding = "DB"
database_name = "proxy-db"
database_id = "PASTE_YOUR_DATABASE_ID_HERE"